export type PosKey = "noun" | "verbAdj";

export type Flashcard = {
  ko: string;
  en: string;
  pos: PosKey;
};

export const FLASHCARDS: Flashcard[] = [
  { ko: "가다", en: "to go", pos: "verbAdj" },
  { ko: "오다", en: "to come", pos: "verbAdj" },
  { ko: "보다", en: "to see", pos: "verbAdj" },
  { ko: "먹다", en: "to eat", pos: "verbAdj" },
  { ko: "하다", en: "to do", pos: "verbAdj" },
  { ko: "돕다", en: "to help", pos: "verbAdj" },
  { ko: "걷다", en: "to walk", pos: "verbAdj" },
  { ko: "묻다", en: "to ask", pos: "verbAdj" },
  { ko: "듣다", en: "to listen", pos: "verbAdj" },
  { ko: "빠르다", en: "to be fast", pos: "verbAdj" },
  { ko: "모르다", en: "to not know", pos: "verbAdj" },
  { ko: "사람", en: "person", pos: "noun" },
  { ko: "물", en: "water", pos: "noun" },
  { ko: "학교", en: "school", pos: "noun" },
  { ko: "친구", en: "friend", pos: "noun" },
  // From screenshots (nouns/phrases)
  { ko: "만나서 반갑습니다", en: "Nice to meet you", pos: "noun" },
  { ko: "의사", en: "doctor", pos: "noun" },
  { ko: "1학년", en: "first-year student", pos: "noun" },
  { ko: "2학년", en: "second-year student", pos: "noun" },
  { ko: "3학년", en: "third-year student", pos: "noun" },
  { ko: "4학년", en: "fourth-year student", pos: "noun" },
  { ko: "중학생", en: "middle school student", pos: "noun" },
  { ko: "한국어", en: "the Korean language", pos: "noun" },
  { ko: "선생님", en: "teacher", pos: "noun" },
  { ko: "우리", en: "my (our), we", pos: "noun" },
  { ko: "회사원", en: "company employee", pos: "noun" },
  { ko: "채소", en: "vegetable", pos: "noun" },
  { ko: "오렌지", en: "orange", pos: "noun" },
  { ko: "사과", en: "apple", pos: "noun" },
  { ko: "오이", en: "cucumber", pos: "noun" },
  { ko: "토마토", en: "tomato", pos: "noun" },
  { ko: "누나", en: "older sister (for male)", pos: "noun" },
  { ko: "동생", en: "younger sibling", pos: "noun" },
  { ko: "일본어", en: "the Japanese language", pos: "noun" },
  { ko: "여자", en: "female", pos: "noun" },
  { ko: "아버지", en: "father", pos: "noun" },
  { ko: "말레이시아", en: "Malaysia", pos: "noun" },
  { ko: "어머니", en: "mother", pos: "noun" },
  { ko: "형", en: "older brother (for male)", pos: "noun" },
  { ko: "어디", en: "where", pos: "noun" },
  { ko: "마트", en: "supermarket", pos: "noun" },
  { ko: "음식", en: "food", pos: "noun" },
  { ko: "주로", en: "usually", pos: "noun" },
  { ko: "다운타운", en: "downtown", pos: "noun" },
  { ko: "토론토", en: "Toronto", pos: "noun" },
  { ko: "핸드폰", en: "cell phone", pos: "noun" },
  { ko: "노트북", en: "laptop", pos: "noun" },
  { ko: "여동생", en: "younger sister", pos: "noun" },
  { ko: "남동생", en: "younger brother", pos: "noun" },
  { ko: "기숙사", en: "residence", pos: "noun" },
  { ko: "책", en: "book", pos: "noun" },
  { ko: "연필", en: "pencil", pos: "noun" },
  { ko: "펜", en: "pen", pos: "noun" },
  { ko: "밴쿠버", en: "Vancouver", pos: "noun" },
  { ko: "몬트리올", en: "Montreal", pos: "noun" },
  { ko: "오타와", en: "Ottawa", pos: "noun" },
  { ko: "우유", en: "milk", pos: "noun" },
  { ko: "드라마", en: "drama", pos: "noun" },
  { ko: "선물", en: "gift", pos: "noun" },
  { ko: "여자친구", en: "girlfriend", pos: "noun" },
  { ko: "케이팝", en: "K-pop", pos: "noun" },
  { ko: "자주", en: "often", pos: "noun" },
  { ko: "이름", en: "name", pos: "noun" },
  { ko: "노래", en: "song", pos: "noun" },
  { ko: "남자친구", en: "boyfriend", pos: "noun" },
  { ko: "댄스", en: "dance", pos: "noun" },
  { ko: "일찍", en: "early", pos: "noun" },
  { ko: "한인마트", en: "Korean market", pos: "noun" },
  { ko: "오늘", en: "today", pos: "noun" },
  { ko: "집", en: "house, home", pos: "noun" },
  { ko: "백화점", en: "department store", pos: "noun" },
  { ko: "극장", en: "theatre", pos: "noun" },
  { ko: "식당", en: "restaurant", pos: "noun" },
  { ko: "학교 식당", en: "student cafeteria", pos: "noun" },
  { ko: "서점", en: "bookstore", pos: "noun" },
  { ko: "교실", en: "classroom", pos: "noun" },
  { ko: "커피숍", en: "coffeeshop", pos: "noun" },
  { ko: "수업", en: "class", pos: "noun" },
  { ko: "독일", en: "Germany", pos: "noun" },
  { ko: "컴퓨터", en: "computer", pos: "noun" },
  { ko: "점심", en: "lunch", pos: "noun" },
  { ko: "화장실", en: "washroom", pos: "noun" },
  { ko: "대학생", en: "college student", pos: "noun" },
  { ko: "미국", en: "U.S.A.", pos: "noun" },
  { ko: "일본", en: "Japan", pos: "noun" },
  { ko: "러시아", en: "Russia", pos: "noun" },
  { ko: "고등학생", en: "high school student", pos: "noun" },
  { ko: "인도", en: "India", pos: "noun" },
  { ko: "프랑스", en: "France", pos: "noun" },
  { ko: "베트남", en: "Vietnam", pos: "noun" },
  { ko: "태국", en: "Thailand", pos: "noun" },
  { ko: "영국", en: "U.K.", pos: "noun" },

  // Additional verbs/adjectives from screenshots
  { ko: "살다", en: "to live", pos: "verbAdj" },
  { ko: "장 보다", en: "to do grocery shopping", pos: "verbAdj" },
  { ko: "있다", en: "to have", pos: "verbAdj" },
  { ko: "읽다", en: "to read", pos: "verbAdj" },
  { ko: "괜찮다", en: "to be okay", pos: "verbAdj" },
  { ko: "맛없다", en: "not to be delicious", pos: "verbAdj" },
  { ko: "재미없다", en: "not to be interesting", pos: "verbAdj" },
  { ko: "쇼핑하다", en: "to shop", pos: "verbAdj" },
  { ko: "지내다", en: "to spend time", pos: "verbAdj" },
  { ko: "크다", en: "to be big", pos: "verbAdj" },
  { ko: "자다", en: "to sleep", pos: "verbAdj" },
  { ko: "보내다", en: "to send", pos: "verbAdj" },
  { ko: "만나다", en: "to meet", pos: "verbAdj" },
  { ko: "나쁘다", en: "to be bad", pos: "verbAdj" },
  { ko: "쓰다", en: "to write", pos: "verbAdj" },
  { ko: "배우다", en: "to learn", pos: "verbAdj" },
  { ko: "마시다", en: "to drink", pos: "verbAdj" },
  { ko: "넓다", en: "to be spacious", pos: "verbAdj" },
  { ko: "작다", en: "to be small", pos: "verbAdj" },
  { ko: "숙제하다", en: "to do homework", pos: "verbAdj" },
  { ko: "운동하다", en: "to exercise", pos: "verbAdj" },
  { ko: "공부하다", en: "to study", pos: "verbAdj" },
  { ko: "좋다", en: "to be good, to like", pos: "verbAdj" },
  { ko: "많다", en: "to be many", pos: "verbAdj" },
  { ko: "맛있다", en: "to be delicious", pos: "verbAdj" },
  { ko: "재미있다", en: "to be interesting", pos: "verbAdj" },
  { ko: "없다", en: "to not have, to not exist", pos: "verbAdj" },
  // Common phrases kept as nouns for translation-only
  { ko: "뭐 해요?", en: "What do you do?", pos: "noun" },
  { ko: "어때요?", en: "How is ~?", pos: "noun" },
  { ko: "한국 음식", en: "Korean food", pos: "noun" },
  { ko: "비빔밥", en: "Bibimbap", pos: "noun" },
  { ko: "엄마 음식", en: "Mom's food", pos: "noun" },
  { ko: "한국 책", en: "Korean book", pos: "noun" },
  { ko: "뭐", en: "what", pos: "noun" },
  { ko: "캐나다", en: "Canada", pos: "noun" },
];

export const EN_TO_KO: Record<string, { ko: string; pos: PosKey }> = {
  go: { ko: "가다", pos: "verbAdj" },
  come: { ko: "오다", pos: "verbAdj" },
  see: { ko: "보다", pos: "verbAdj" },
  eat: { ko: "먹다", pos: "verbAdj" },
  do: { ko: "하다", pos: "verbAdj" },
  help: { ko: "돕다", pos: "verbAdj" },
  walk: { ko: "걷다", pos: "verbAdj" },
  ask: { ko: "묻다", pos: "verbAdj" },
  listen: { ko: "듣다", pos: "verbAdj" },
  fast: { ko: "빠르다", pos: "verbAdj" },
  "not know": { ko: "모르다", pos: "verbAdj" },
  person: { ko: "사람", pos: "noun" },
  water: { ko: "물", pos: "noun" },
  school: { ko: "학교", pos: "noun" },
  friend: { ko: "친구", pos: "noun" },
  doctor: { ko: "의사", pos: "noun" },
  "first-year student": { ko: "1학년", pos: "noun" },
  "second-year student": { ko: "2학년", pos: "noun" },
  "third-year student": { ko: "3학년", pos: "noun" },
  "fourth-year student": { ko: "4학년", pos: "noun" },
  "middle school student": { ko: "중학생", pos: "noun" },
  "the Korean language": { ko: "한국어", pos: "noun" },
  teacher: { ko: "선생님", pos: "noun" },
  we: { ko: "우리", pos: "noun" },
  our: { ko: "우리", pos: "noun" },
  "company employee": { ko: "회사원", pos: "noun" },
  vegetable: { ko: "채소", pos: "noun" },
  orange: { ko: "오렌지", pos: "noun" },
  apple: { ko: "사과", pos: "noun" },
  cucumber: { ko: "오이", pos: "noun" },
  tomato: { ko: "토마토", pos: "noun" },
  "older sister for male": { ko: "누나", pos: "noun" },
  "younger sibling": { ko: "동생", pos: "noun" },
  "the Japanese language": { ko: "일본어", pos: "noun" },
  female: { ko: "여자", pos: "noun" },
  father: { ko: "아버지", pos: "noun" },
  malaysia: { ko: "말레이시아", pos: "noun" },
  mother: { ko: "어머니", pos: "noun" },
  "older brother for male": { ko: "형", pos: "noun" },
  where: { ko: "어디", pos: "noun" },
  supermarket: { ko: "마트", pos: "noun" },
  food: { ko: "음식", pos: "noun" },
  usually: { ko: "주로", pos: "noun" },
  downtown: { ko: "다운타운", pos: "noun" },
  toronto: { ko: "토론토", pos: "noun" },
  cellphone: { ko: "핸드폰", pos: "noun" },
  laptop: { ko: "노트북", pos: "noun" },
  "younger sister": { ko: "여동생", pos: "noun" },
  "younger brother": { ko: "남동생", pos: "noun" },
  residence: { ko: "기숙사", pos: "noun" },
  book: { ko: "책", pos: "noun" },
  pencil: { ko: "연필", pos: "noun" },
  pen: { ko: "펜", pos: "noun" },
  vancouver: { ko: "밴쿠버", pos: "noun" },
  montreal: { ko: "몬트리올", pos: "noun" },
  ottawa: { ko: "오타와", pos: "noun" },
  milk: { ko: "우유", pos: "noun" },
  drama: { ko: "드라마", pos: "noun" },
  gift: { ko: "선물", pos: "noun" },
  girlfriend: { ko: "여자친구", pos: "noun" },
  kpop: { ko: "케이팝", pos: "noun" },
  often: { ko: "자주", pos: "noun" },
  name: { ko: "이름", pos: "noun" },
  song: { ko: "노래", pos: "noun" },
  boyfriend: { ko: "남자친구", pos: "noun" },
  dance: { ko: "댄스", pos: "noun" },
  early: { ko: "일찍", pos: "noun" },
  "korean market": { ko: "한인마트", pos: "noun" },
  today: { ko: "오늘", pos: "noun" },
  house: { ko: "집", pos: "noun" },
  home: { ko: "집", pos: "noun" },
  "department store": { ko: "백화점", pos: "noun" },
  theatre: { ko: "극장", pos: "noun" },
  restaurant: { ko: "식당", pos: "noun" },
  "student cafeteria": { ko: "학교 식당", pos: "noun" },
  bookstore: { ko: "서점", pos: "noun" },
  classroom: { ko: "교실", pos: "noun" },
  coffeeshop: { ko: "커피숍", pos: "noun" },
  class: { ko: "수업", pos: "noun" },
  germany: { ko: "독일", pos: "noun" },
  computer: { ko: "컴퓨터", pos: "noun" },
  lunch: { ko: "점심", pos: "noun" },
  washroom: { ko: "화장실", pos: "noun" },
  "college student": { ko: "대학생", pos: "noun" },
  "u.s.a.": { ko: "미국", pos: "noun" },
  japan: { ko: "일본", pos: "noun" },
  russia: { ko: "러시아", pos: "noun" },
  "high school student": { ko: "고등학생", pos: "noun" },
  india: { ko: "인도", pos: "noun" },
  france: { ko: "프랑스", pos: "noun" },
  vietnam: { ko: "베트남", pos: "noun" },
  thailand: { ko: "태국", pos: "noun" },
  "u.k.": { ko: "영국", pos: "noun" },
  live: { ko: "살다", pos: "verbAdj" },
  "do grocery shopping": { ko: "장 보다", pos: "verbAdj" },
  have: { ko: "있다", pos: "verbAdj" },
  read: { ko: "읽다", pos: "verbAdj" },
  "be okay": { ko: "괜찮다", pos: "verbAdj" },
  "not be delicious": { ko: "맛없다", pos: "verbAdj" },
  "not be interesting": { ko: "재미없다", pos: "verbAdj" },
  shop: { ko: "쇼핑하다", pos: "verbAdj" },
  "spend time": { ko: "지내다", pos: "verbAdj" },
  "be big": { ko: "크다", pos: "verbAdj" },
  sleep: { ko: "자다", pos: "verbAdj" },
  send: { ko: "보내다", pos: "verbAdj" },
  meet: { ko: "만나다", pos: "verbAdj" },
  "be bad": { ko: "나쁘다", pos: "verbAdj" },
  write: { ko: "쓰다", pos: "verbAdj" },
  learn: { ko: "배우다", pos: "verbAdj" },
  drink: { ko: "마시다", pos: "verbAdj" },
  "be spacious": { ko: "넓다", pos: "verbAdj" },
  "be small": { ko: "작다", pos: "verbAdj" },
  "do homework": { ko: "숙제하다", pos: "verbAdj" },
  exercise: { ko: "운동하다", pos: "verbAdj" },
};
